---

## Playbook for Ubuntu 18.04 machine DevOps dedicated setup  
## Author: @jkogut

- name: run the playbook tasks on the localhost
  hosts: localhost
  become: yes
  tasks:

## Be sure about machine that is being installed
  - name: print out the hostname of target
    command: hostname

## APT update & packages upgrade  
  - name: update the apt package index i.e. apt-get update
    apt: update_cache=yes

  - name: upgrade system packages i.e. apt-get upgrade
    apt: upgrade=yes

## Common packages installation with APT
  - name: install common packages with APT
    apt: name={{ item }} state=present
    with_items:
      - vim
      - curl
      - ack
      - ccze
      - htop
      - shutter
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - jq
      - ipython
      - python-pip
      - docker-compose
      - default-jre
      - default-jdk
      - openjdk-8-jdk
      - openjdk-8-jre
      - scala
      - golang  
      - kafkacat
      - iotop
      - sysdig
      - net-tools
      - glances
      - chromium-browser
      - terminator
      - mysql-client
      - tmux
      - pv
      - openconnect
      - p7zip-full
      - p7zip-rar
      - tree
    tags:
      - apt

## Custom packages installation with PIP
  - name: install common packages with PIP
    pip: name={{ item }}
    with_items:
      - google-auth # for using ansible@gcp
      - ruamel.yaml # better yaml support
      - awscli      # awscli
      - snakebite   # python HDFS client
      - kubernetes
      - jinja2
    tags:
      - pip

## Custom packages installation with SNAP 
  - name: install intellij-idea-community edition with snap
    command: snap install intellij-idea-community --classic
    tags:
      - intellij

## Docker related stuff
  - name: Add Docker GPG key
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg
    tags:
      - docker

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
      state: present
      filename: docker
    tags:
      - docker

  - name: Install Docker-ce
    apt:
      name: docker-ce
      state: present
    tags:
      - docker
      
## K8S related stuff
  - name: install kubectl + helm with snap
    # snap module is supported for ansible >= 2.8
    # https://docs.ansible.com/ansible/latest/modules/snap_module.html#snap-module
    command: snap install {{ item }} --classic
    with_items:
      - helm
      - kubectl
    tags:
      - snap-k8s

  - name: install kubectx from github repo
    git:
      repo: https://github.com/ahmetb/kubectx
      dest: /opt/github/kubectx
    tags: 
      - kubectx

  - name: create syslinks for kubectx scripts from github
    file: 
      src: "/opt/github/kubectx/{{ item.src }}"
      dest: "/usr/local/bin/{{ item.dest }}"
      state: link
    with_items:
      - { src: kubectx, dest: kubectx }
      - { src: kubens, dest: kubens }
    tags:
      - kubectx

  - name: download and uncompress eksctl
    shell: 
      curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp; 
      mv /tmp/eksctl /usr/local/bin
    tags:
      - eksctl

  - name: download and uncompress aws-iam-authenticator
    shell: 
      curl -o /tmp/aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator;
      mv /tmp/aws-iam-authenticator /usr/local/bin; chmod +x /usr/local/bin/aws-iam-authenticator
    tags:
      - aws-iam-authenticator